create table if not exists snowflake_copy_history (
    file_name string,
    stage_location string,
    last_load_time timestamp,
    row_count bigint,
    row_parsed bigint,
    file_size bigint,
    first_error_message string,
    first_error_line_number bigint,
    first_error_character_pos bigint,
    first_error_column_name string,
    error_count bigint,
    error_limit bigint,
    status string,
    table_id bigint,
    table_name string,
    table_schema_id bigint,
    table_schema_name string,
    table_catalog_id bigint,
    table_catalog_name string,
    pipe_catalog_name string,
    pipe_schema_name string,
    pipe_name string,
    pipe_received_time timestamp,
    first_commit_time timestamp
)