services:

  snowguard:
    image: snowguard
    build:
      context: ..
      dockerfile: .docker/snowguard.Dockerfile
    container_name: snowguard
    ports:
      - "50052:8088"
      - "50051:50051"
    environment:
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE}
      - SUPERSET_ADMIN_KEY=${SUPERSET_ADMIN_KEY}
    # volumes:
    #   - ../:/home/snowguard
    #   - ./superset_config.py:/app/superset/config.py
