services:

  skiguard:
    image: skiguard
    build:
      context: ..
      dockerfile: .docker/skiguard.Dockerfile
    container_name: skiguard
    ports:
      - "8088:8088"
      - "50051:50051"
    environment:
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE}
      - SUPERSET_ADMIN_KEY=${SUPERSET_ADMIN_KEY}
      - SKIGUARD_LICENSE_KEY=${SKIGUARD_LICENSE_KEY}
    volumes:
      - ./skiguard/test:/home/skiguard/test
